### ISSUE TITLE
修正を受け付けるための窓口を記載する

### ISSUE THREAD

**Issue by pankona** [pankona/techbookfest11#4]
読んでくれた方がもしかしたら間違いに気付いて修正を送ってくれる (気付かせてくれる) かもしれないので、どこにコンタクトすればよいのかは最低限載せておいたほうがよいかしら、と思った。
- プルリクエストを受け付ける形にしちゃってもいいかもしれない
- そうでなかったらメールとか
- Google Form とかもあるかもしれないが、いつまで維持すればよいか微妙という懸念はある
- issue テンプレートを用意しておいてそこに誘導するみたいな形でもいいかもしれない

**Comment by pankona** [comment]
GitHub issue template にするの良さそうだな、等と思っていたけど、それってつまり GitHub アカウントがないと使えないっていうことに気がついた。他の手段も用意しといたほうがいいかもね。まあメールか。

**Comment by kachick** [comment]
GitHub アカウントがない人をこの本の想定読者に入れなくて良いと思うけど・・・ 😅

**Comment by pankona** [comment]
作った
![image](https://user-images.githubusercontent.com/6533008/124480329-1b948e00-dde2-11eb-876d-2a840dd70d69.png)

**Comment by pankona** [comment]
issue へのリンクはこんな感じでまあまあ長い

https://github.com/pankona/techbookfest11/issues/new?assignees=pankona&labels=bug&template=errata.yaml&title=%E8%AA%A4%E5%AD%97%E8%84%B1%E5%AD%97%E3%81%AE%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B

電子書籍だってことで、このへんは適当に [リンク入りテキスト](https://github.com/pankona/techbookfest11/issues/new?assignees=pankona&labels=bug&template=errata.yaml&title=%E8%AA%A4%E5%AD%97%E8%84%B1%E5%AD%97%E3%81%AE%E3%81%8A%E7%9F%A5%E3%82%89%E3%81%9B) にしちゃえばいいか。便利。

**Comment by pankona** [comment]
@kachick 

それはさもありなん

**Comment by pankona** [comment]
QR コードなどを入れ込んで対応した。本件は close する。
