### ISSUE TITLE
誤字脱字のお知らせ（太字命令のtypo？）

### ISSUE THREAD

**Issue by sylph01** [pankona/techbookfest11#9]
### どの部分に誤りがありますか？ページ数と該当箇所を教えて下さい :pray:

p14

![Screenshot_20210710_132341](https://user-images.githubusercontent.com/809530/125151581-1341a780-e182-11eb-87dc-4d28d85ded0c.png)

### 正しくはどのようになっているべきでしょうか？ :thinking:

- 「メンバーの上位互換ではない」が太字を意図しているものと思います
- がこれが意図した入力の可能性（Vimのコマンド…？）もあるので100%の自信はないです

**Comment by pankona** [comment]
ご指摘ありがとうございます！さっそく直します！

**Comment by pankona** [comment]
https://github.com/pankona/techbookfest11/releases/tag/v1.0.1 にて本件の修正が反映されます。
いましがた再審査に出しました。本 issue は、v1.0.1 の審査が完了して書籍が購入が可能になった時点クローズする予定です。
@sylph01 ありがとうございました！ 👍

**Comment by pankona** [comment]
v1.0.1 の審査が済んで販売が開始されました。速くない...？
本 issue を close します！
